---
platform: linux

image_resource:
  type: docker-image
  source: {repository: sense12/python-builder}

outputs:
- name: python-dist

run:
  path: sh
  args:
  - -exc
  - |
    cd /build
    ls -l
    make build
    make verify-build
    ls -la dist
    cd -
    mv /build/dist/*.tar.gz python-dist/release.tar.gz
    ls -la python-build
