---
platform: linux

image_resource:
  type: docker-image
  source: {repository: sense12/python-builder, tag: 0.1.0-alpha1 }

inputs:
- name: orchastrator
- name: sense12-api

# outputs:
# - name: python-dist

run:
  path: sh
  args:
  - -exc
  - |
    alias gmake="make -f /files/Makefile"
    cp sense12-api/* .
    gmake venv dist
    ls -l
    ls -la dist
    make verify-build
    # mv ./dist/*.tar.gz python-dist/release.tar.gz
    # ls -la python-dist
